language: node_js
sudo: required
dist: trusty
node_js:
  - '6'
cache:
  directories:
    - $HOME/.yarn-cache
branches:
  except:
    - /^v\d/
install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn
  - yarn install
  - yarn add bower
  - bower install
before_script:
  - npm run lint
script:
  - npm test
before_deploy:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: abdonrd-develop
    token: $FIREBASE_TOKEN
    on:
      branch: develop
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: abdonrd
    token: $FIREBASE_TOKEN
    on:
      branch: master
